title: 개발블로그
email: charles9306@icloud.com
description: 안녕하세요. 여러분
url: "https://get6.github.io"
logo: nes-kirby
theme: jekyll-theme-8bit
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
#paginate: 2
social:
  twitter: https://twitter.com/charles9306
  facebook: https://facebook.com/seongjun.hwang1
  github: https://github.com/get6
  #youtube: https://youtube.com/channel/ID
  #google: https://plus.google.com/username
  #medium: https://medium.com/@username
  #twitch: https://twitch.com/username
  #reddit: https://www.reddit.com/user/username
  #whatsapp: tel:+5541999999999
  gmail: mailto:tjdwns075@gmail.com
  #linkedin: https://www.linkedin.com/in/username
  disqus:
  shortname: jekyll-theme-8bit